spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ehwjs2019!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


